name: Lint Codebase

on: [push]

jobs:
  eslint:
    runs-on: node

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint