name: discord bot tests

on: [push]

jobs:
  discord_bot_tests:
    runs-on: node
    name: discord bot tests
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
    - name: install dependencies
      run: npm install
    - name: run tests
      run: npm test 